version: 2.1
jobs:
  build:
    parameters:
      pr-version:
        type: string
        default: "1.2.0"
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      DKTL_VERSION: "4.0.0"
    steps:
      - checkout
      - run:
          name: "Setup variables"
          command: |
            echo $CIRCLE_BRANCH
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Install Dependencies and Run Jest Tests
          command: |
            nvm install 10
            npm install
            npm rebuild node-sass
            node --version
            npm run test
      - run:
          name: Install DKTL
          command: |
            cd ~
            git clone -b $DKTL_VERSION https://github.com/GetDKAN/dkan-tools.git ~/dkan-tools
            echo "export PATH=~/dkan-tools/bin:$PATH" >> $BASH_ENV
            which dktl
      - run:
          name: Run cypress tests
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            mkdir ~/sandbox
            cd ~/sandbox
            dktl init
            dktl make
            dktl install
            dktl install:sample
            dktl frontend:install
            git clone --single-branch -b $CIRCLE_BRANCH https://github.com/GetDKAN/data-catalog-components.git
            version=$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' package.json)
            echo $version
            cd data-catalog-compontents
            npm install --unsafe-perms
            npm pack --unsafe-perm
            cd ~/sandbox/src/frontend
            npm install ../../data-catalog-components/civicactions-data-catalog-components-<< $version >>.tgz
            cat package.json
            rm -rf node_modules
            rm package-lock.json
            npm install
            cat node_modules/@civicactions/data-catalog-components/package.json
            dktl frontend:build
            dktl drush cr
            dktl frontend:test
      - store_artifacts:
          path: ~/sandbox/src/frontend/cypress/screenshots
      - store_artifacts:
          path: ~/sandbox/src/frontend/cypress/videos
