version: '2.1'
orbs:
  docker: circleci/docker@2.2.0

jobs:
  build:
    parallelism: 1
    docker:
      - image: cimg/node:23.11.0
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Run Jest
          command: npm run test