version: 2.1
jobs:
  build:
    parameters:
      pr-version:
        type: string
        default: "1.2.0"
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      DRUPAL_VERSION: V8
    steps:
      - checkout
      # - restore_cache:
      #     key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: "Setup variables"
          command: |
            echo $CIRCLE_BRANCH
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Install Dependencies and Run Jest Tests
          command: |
            nvm install 10
            npm install
            npm rebuild node-sass
            node --version
            npm run test
      - run:
          name: Install DKTL
          command: |
            cd ~
            git clone --single-branch --depth 1 https://github.com/GetDKAN/dkan-tools.git
            chmod 777 ./dkan-tools/bin/dktl
            export PATH=$PATH:~/dkan-tools/bin
            which dktl
      - run:
          name: Initialize Project
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            mkdir ~/sandbox
            cd ~/sandbox
            dktl init
      - run:
          name: Get Drupal
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/sandbox
            dktl get 8.8.5
      - run:
          name: Make DKAN
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/sandbox
            dktl make --frontend
      - run:
          name: Install site
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/sandbox
            dktl install
      - run:
          name: Run cypress tests
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/sandbox
            dktl dc up -d
            dktl drush user:create testuser --password="2jqzOAnXS9mmcLasy"
            dktl drush en sample_content frontend -y
            dktl drush dkan:sample-content:create
            dktl drush queue:run datastore_import
            dktl drush dkan:metastore-search:rebuild-tracker
            dktl drush search-api-index
            dktl dc exec web chmod -R 777 /var/www/docroot/data-catalog-frontend
            dktl dc run cli git clone --single-branch -b $CIRCLE_BRANCH https://github.com/GetDKAN/data-catalog-components.git
            dktl dc run cli npm install --prefix /var/www/data-catalog-components --unsafe-perm
            dktl dc run -w /var/www/data-catalog-components cli npm pack --unsafe-perm
            dktl dc run -w /var/www/docroot/data-catalog-frontend cli npm install ../../data-catalog-components/civicactions-data-catalog-components-<< parameters.pr-version >>.tgz
            dktl dc run cli cat /var/www/docroot/data-catalog-frontend/package.json
            dktl dc run -w /var/www/docroot/data-catalog-frontend cli rm -rf node_modules
            dktl dc run -w /var/www/docroot/data-catalog-frontend cli rm package-lock.json
            dktl dc exec cli npm install --prefix /var/www/docroot/data-catalog-frontend --unsafe-perm
            dktl dc run cli cat /var/www/docroot/data-catalog-frontend/node_modules/@civicactions/data-catalog-components/package.json
            dktl frontend:build
            dktl dc exec web chmod -R 777 /var/www/docroot/sites/default/files/dkan-tmp
            dktl drush cr
            dktl dkan:test-cypress frontend
      - store_artifacts:
          path: ~/sandbox/src/frontend/cypress/screenshots
      - store_artifacts:
          path: ~/sandbox/src/frontend/cypress/videos
