version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: cimg/node:16.14.2
    environment:
      TEST_RESULTS: /tmp/test-results
      DRUPAL_VERSION: V8
    steps:
      - checkout
      - run: node --version
      - run:
          name: "Setup variables"
          command: |
            echo $CIRCLE_BRANCH
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Jest Tests
          command: npm test
